[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch",
    "numpy",
    "gym",
    "scikit-image",
    "opencv-python",
    "pillow",
    "shutil"
]
build-backend = "setuptools.build_meta"